### ISSUE TITLE
NOTIFY

### ISSUE THREAD

**Issue by MG1937** [sysiiii/keepalive#5]
本质就是个循环判断FLAG_STOPPED加startInstrumention,谷歌上个月都修了,赶紧删项目吧,别丢人了,保活的方案大把大把.就你这个最拉跨还抄的不知道谁的方案

**Comment by MG1937** [comment]
顺带一提后台弹窗是各手机厂的0day,早都修完了,比如小米的就是Intent里面加个小米自己定义的成员,parcel就能实现了,MIUI12.5就修了

**Comment by LeoChen-CoreMind** [comment]
怎么联系你

**Comment by LeoChen-CoreMind** [comment]
你的后台保活多少钱可以买？qq:1708636545
